// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection. Neon/Vercel Postgres
    // expose this as DIRECT_URL alongside the pooled DATABASE_URL the app
    // runtime uses (see src/lib/prisma.ts). Falls back to DATABASE_URL for
    // local dev where there's no pooler in front of Postgres.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
